website/books/urls.py
from django.urls import path
from .views import BookDetailView, ImageSearchView, ImageProcessingView, BookRecommendationsView

app_name = 'books'

urlpatterns = [
    path('', ImageSearchView.as_view(), name='upload_image'),
    path('processing/', ImageProcessingView.as_view(), name='image_search_processing'),
    path('recommendations/', BookRecommendationsView.as_view(), name='book_recommendations'),
    path('book/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
]

website/home/urls.py
from django.urls import path
from . import views

app_name = 'home'  # Changed from 'users' to 'home'

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='index'),
    # You can also add an alias for 'landing_page' if needed elsewhere
    path('landing/', views.LandingPageView.as_view(), name='landing_page'),
]

website/website/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    path("", include("home.urls")), 
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),
    path('accounts/', include('registration.backends.default.urls')),
    path("books/", include("books.urls")),  # Include the books app URLs
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("users/", include("users.urls")),  # Include the users app URLs
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

website/website/templates/components/book_card.html
{% load static %}
<div class="book-card">
    <div class="add-icon-container">
        <button class="add-icon-btn">
            <img src="{% static 'images/icons/add-icon.png' %}"
                 data-hover="{% static 'images/icons/add-icon-alternate.png' %}"
                 data-src="{% static 'images/icons/add-icon.png' %}"
                 alt="Add Icon"
                 class="add-icon hover-swap" />
        </button>
    </div>
    <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
        {% if book.image_url_large %}
            <img src="{{ book.image_url_large }}" alt="{{ book.title }}" class="cover-img">
        {% elif book.image_url %}
            <img src="{{ book.image_url }}" alt="{{ book.title }}" class="cover-img">
        {% else %}
            <div class="cover-placeholder">
                <p>No Cover Available</p>
            </div>
        {% endif %}
    </div>
    
    <a href="{% url 'books:book_detail' pk=book.pk %}" class="card-btn">
        <span class="glow"></span>
        More Info
    </a>
</div>

website/website/templates/components/header.html
{% load static %}

<header class="header2">
    <div class="header-left-icons" style="display: flex; align-items: center; gap: 10px;">
        <a href="#" onclick="history.back(); return false;" aria-label="Go back">
            <img src="{% static 'images/icons/back-icon.png' %}"
                 data-hover="{% static 'images/icons/back-icon-alternate.png' %}"
                 data-src="{% static 'images/icons/back-icon.png' %}"
                 alt="Back Icon"
                 class="header-icon hover-swap" />
        </a>

        <a href="/">
            <img src="{% static 'images/icons/home-icon.png' %}"
                 data-hover="{% static 'images/icons/home-icon-alternate.png' %}"
                 data-src="{% static 'images/icons/home-icon.png' %}"
                 alt="Home Icon"
                 class="header-icon hover-swap" />
        </a>

        <!-- Divider -->
        <div style="width: 2px; height: 50px; background-color: white; margin: 0 15px;"></div>

        <a href="{% url 'wagtailadmin_login' %}" class="login-btn" style="margin-left: 10px;">
            <span class="login"></span>
            Login
        </a>
    </div>

    <img src="{% static 'images/novelscape-logo.png' %}" alt="Novelscape Logo" class="header-logo" />
</header>